# Generated by Django 2.0.3 on 2018-03-15 13:47

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('ParcelType', 'ParcelType'), ('ParcelServiceType', 'ParcelServiceType'), ('ParcelDestType', 'ParcelDestType'), ('SendingMethod', 'SendingMethod'), ('ExtraTime', 'ExtraTime'), ('SPSReceivedTimeType', 'SPSReceivedTimeType'), ('SPSDestinationType', 'SPSDestinationType'), ('SPSParcelType', 'SPSParcelType'), ('InsuranceType', 'InsuranceType')], max_length=200, verbose_name='group type')),
                ('type', models.CharField(max_length=200, verbose_name='type')),
                ('value', models.PositiveIntegerField(verbose_name='value')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaticTypesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('lable', models.CharField(blank=True, max_length=50)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='barcode.StaticTypes')),
            ],
            options={
                'verbose_name': 'static types Translation',
                'db_table': 'barcode_statictypes_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='statictypestranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
